import os
DEBUG=True
SQLALCHEMY_DATABASE_URI="sqlite:///dat.db"
SQLALCHEMY_TRACK_MODIFICATIONS=False
PROPAGATE_EXCEPTIONS=True
JWT_SECRET_KEY=os.getenv("JWT_SECRET_KEY") 
API_TITLE="Stores REST API"
API_VERSION="v1"
OPENAPI_VERSION="3.0.3"
OPENAPI_URL_PREFIX="/"
OPENAPI_SWAGGER_UI_PATH= "/swagger-ui"
OPENAPI_SWAGGER_UI_URL="https://cdn.jsdelivr.net/npm/swagger-ui-dist/"
UPLOADED_IMAGES_DEST=os.path.join('static','images')
MAX_CONTENT_LENGTH='10*1024*1024'